###########################################
#Makefile for my C++ programs
###########################################

TRG = main
OBJ = main.o
SRC = main.cc
VPATH = /home/miku/learn/Learning\ C++
CC = /usr/bin/clang
CXX = /usr/bin/clang++
FORMAT = /usr/bin/clang-format
C_FLAGS = -std=c18 -Wall -Wno-unused
CXX_FLAGS = -std=c++20 -Wall -Wno-unused
DEBUG = -g -O0
RELEASE = -static -O3
LINK_FLAGS = -no-pie
LIBS = -lpthread
CLANGXX_FLAGS = -stdlib=libc++
CLANGXX_LINK_FLAGS = -lc++ -nostdlib++

.PHONY : all
all :
	cd 0.template && make
	cd 1.array && make
	cd 2.vector && make
	cd 3.deque && make
	cd 4.list && make
	cd 5.forward_list && make
	cd 6.set && make
	cd 7.multiset && make
	cd 8.map && make
	cd 9.multimap && make
	cd 10.unordered_set && make
	cd 11.unordered_multiset && make
	cd 12.unordered_map && make
	cd 13.unordered_multimap && make
	cd 14.stack && make
	cd 15.queue && make
	cd 16.priority_queue && make
	cd 17.thread && make
	cd 18.count && make
	cd 19.count_if && make
	cd 20.find && make
	cd 21.find_if && make
	cd 22.copy_if && make
	cd 23.remove_if && make
	cd 24.transform && make
	cd 25.bind && make
	cd 26.lambda && make
	cd 27.function_object && make
	cd 28.minmax_element && make
	cd 29.equal && make

format :
	cd 0.template && make format
	cd 1.array && make format
	cd 2.vector && make format
	cd 3.deque && make format
	cd 4.list && make format
	cd 5.forward_list && make format
	cd 6.set && make format
	cd 7.multiset && make format
	cd 8.map && make format
	cd 9.multimap && make format
	cd 10.unordered_set && make format
	cd 11.unordered_multiset && make format
	cd 12.unordered_map && make format
	cd 13.unordered_multimap && make format
	cd 14.stack && make format
	cd 15.queue && make format
	cd 16.priority_queue && make format
	cd 17.thread && make format
	cd 18.count && make format
	cd 19.count_if && make format
	cd 20.find && make format
	cd 21.find_if && make format
	cd 22.copy_if && make format
	cd 23.remove_if && make format
	cd 24.transform && make format
	cd 25.bind && make format
	cd 26.lambda && make format
	cd 27.function_object && make format
	cd 28.minmax_element && make format
	cd 29.equal && make format

clean :
	cd 0.template && make clean
	cd 1.array && make clean
	cd 2.vector && make clean
	cd 3.deque && make clean
	cd 4.list && make clean
	cd 5.forward_list && make clean
	cd 6.set && make clean
	cd 7.multiset && make clean
	cd 8.map && make clean
	cd 9.multimap && make clean
	cd 10.unordered_set && make clean
	cd 11.unordered_multiset && make clean
	cd 12.unordered_map && make clean
	cd 13.unordered_multimap && make clean
	cd 14.stack && make clean
	cd 15.queue && make clean
	cd 16.priority_queue && make clean
	cd 17.thread && make clean
	cd 18.count && make clean
	cd 19.count_if && make clean
	cd 20.find && make clean
	cd 21.find_if && make clean
	cd 22.copy_if && make clean
	cd 23.remove_if && make clean
	cd 24.transform && make clean
	cd 25.bind && make clean
	cd 26.lambda && make clean
	cd 27.function_object && make clean
	cd 28.minmax_element && make clean
	cd 29.equal && make clean