###########################################
#Makefile for my C programs
###########################################

TRG = main
OBJ = main.o
SRC = main.c
VPATH = /home/miku/learn/Learning\ C
CC = /usr/bin/clang
CXX = /usr/bin/clang++
FORMAT = /usr/bin/clang-format
C_FLAGS = -std=c18 -Wall -Wno-unused
CXX_FLAGS = -std=c++20 -Wall -Wno-unused
DEBUG = -g -O0
RELEASE = -static -O3
LINK_FLAGS = -no-pie
LIBS = -lpthread
CLANGXX_FLAGS = -stdlib=libc++
CLANGXX_LINK_FLAGS = -lc++ -nostdlib++

.PHONY : all
all :
	cd 00.template && make
	cd 01.macro && make
	cd 02.static_library && make
	cd 03.dynamic_library && make
	cd 04.dlsym && make
	cd 05.open && make
	cd 06.write && make
	cd 07.read && make
	cd 08.fopen && make
	cd 09.line_buffer && make
	cd 10.all_buffer && make
	cd 11.mkdir && make
	cd 12.opendir && make
	cd 13.readdir && make
	cd 14.fork && make
	cd 15.vfork && make
	cd 16.pipe && make
	cd 17.mkfifo && make
	cd 18.kill && make
	cd 19.raise && make
	cd 20.alarm && make
	cd 21.pause && make
	cd 22.signal && make
	cd 23.shmget && make
	cd 24.ftok && make
	cd 25.shmat && make
	cd 26.shmctl && make
	cd 27.msgget && make
	cd 28.msgsnd && make
	cd 29.msgrcv && make
	cd 30.semget && make
	cd 31.semop && make
	cd 32.one_producer_one_consumer_sem && make
	cd 33.multi_producer_multi_consumer_sem && make
	cd 34.pthread_create && make
	cd 35.pthread_exit && make
	cd 36.pthread_join && make
	cd 37.pthread_detach && make
	cd 38.pthread_cancel && make
	cd 39.pthread_kill && make
	cd 40.sigaction && make
	cd 41.pthread_cleanup && make
	cd 42.pthread_mutex && make
	cd 43.pthread_rwlock && make
	cd 44.pthread_cond && make
	cd 45.one_producer_one_consumer_cond && make
	cd 46.multi_producer_multi_consumer_cond && make
	cd 47.perror && make
	cd 48.union && make
	cd 49.threadpool && make

format :
	cd 00.template && make format
	cd 01.macro && make format
	cd 02.static_library && make format
	cd 03.dynamic_library && make format
	cd 04.dlsym && make format
	cd 05.open && make format
	cd 06.write && make format
	cd 07.read && make format
	cd 08.fopen && make format
	cd 09.line_buffer && make format
	cd 10.all_buffer && make format
	cd 11.mkdir && make format
	cd 12.opendir && make format
	cd 13.readdir && make format
	cd 14.fork && make format
	cd 15.vfork && make format
	cd 16.pipe && make format
	cd 17.mkfifo && make format
	cd 18.kill && make format
	cd 19.raise && make format
	cd 20.alarm && make format
	cd 21.pause && make format
	cd 22.signal && make format
	cd 23.shmget && make format
	cd 24.ftok && make format
	cd 25.shmat && make format
	cd 26.shmctl && make format
	cd 27.msgget && make format
	cd 28.msgsnd && make format
	cd 29.msgrcv && make format
	cd 30.semget && make format
	cd 31.semop && make format
	cd 32.one_producer_one_consumer_sem && make format
	cd 33.multi_producer_multi_consumer_sem && make format
	cd 34.pthread_create && make format
	cd 35.pthread_exit && make format
	cd 36.pthread_join && make format
	cd 37.pthread_detach && make format
	cd 38.pthread_cancel && make format
	cd 39.pthread_kill && make format
	cd 40.sigaction && make format
	cd 41.pthread_cleanup && make format
	cd 42.pthread_mutex && make format
	cd 43.pthread_rwlock && make format
	cd 44.pthread_cond && make format
	cd 45.one_producer_one_consumer_cond && make format
	cd 46.multi_producer_multi_consumer_cond && make format
	cd 47.perror && make format
	cd 48.union && make format
	cd 49.threadpool && make format

clean :
	cd 00.template && make clean
	cd 01.macro && make clean
	cd 02.static_library && make clean
	cd 03.dynamic_library && make clean
	cd 04.dlsym && make clean
	cd 05.open && make clean
	cd 06.write && make clean
	cd 07.read && make clean
	cd 08.fopen && make clean
	cd 09.line_buffer && make clean
	cd 10.all_buffer && make clean
	cd 11.mkdir && make clean
	cd 12.opendir && make clean
	cd 13.readdir && make clean
	cd 14.fork && make clean
	cd 15.vfork && make clean
	cd 16.pipe && make clean
	cd 17.mkfifo && make clean
	cd 18.kill && make clean
	cd 19.raise && make clean
	cd 20.alarm && make clean
	cd 21.pause && make clean
	cd 22.signal && make clean
	cd 23.shmget && make clean
	cd 24.ftok && make clean
	cd 25.shmat && make clean
	cd 26.shmctl && make clean
	cd 27.msgget && make clean
	cd 28.msgsnd && make clean
	cd 29.msgrcv && make clean
	cd 30.semget && make clean
	cd 31.semop && make clean
	cd 32.one_producer_one_consumer_sem && make clean
	cd 33.multi_producer_multi_consumer_sem && make clean
	cd 34.pthread_create && make clean
	cd 35.pthread_exit && make clean
	cd 36.pthread_join && make clean
	cd 37.pthread_detach && make clean
	cd 38.pthread_cancel && make clean
	cd 39.pthread_kill && make clean
	cd 40.sigaction && make clean
	cd 41.pthread_cleanup && make clean
	cd 42.pthread_mutex && make clean
	cd 43.pthread_rwlock && make clean
	cd 44.pthread_cond && make clean
	cd 45.one_producer_one_consumer_cond && make clean
	cd 46.multi_producer_multi_consumer_cond && make clean
	cd 47.perror && make clean
	cd 48.union && make clean
	cd 49.threadpool && make clean